function layout(cell)
    local subref = pcell.create_layout("__test/align_sub", "sub")
    local subcenter = cell:add_child(subref, "sub1")
    subcenter:translate(2000, 2000)
    local subtop = cell:add_child(subref, "subtop")
    subtop:abut_top(subcenter)
    subtop:align_left(subcenter)
    local subbottom = cell:add_child(subref, "subbottom")
    subbottom:abut_bottom(subcenter)
    subbottom:align_left(subcenter)
    local subleft = cell:add_child(subref, "subleft")
    subleft:abut_left(subcenter)
    subleft:align_bottom(subcenter)
    local subright = cell:add_child(subref, "subright")
    subright:abut_right(subcenter)
    subright:align_bottom(subcenter)
end
