return {
    ["Minimum Active Width"]                        = 200,
    ["Minimum Source/Drain Contact Region Size"]    = 200,
    ["Minimum Active Contact Region Size"]          = 200,
    ["Minimum Gate Contact Region Size"]            = 200,
    ["Minimum Active Contact Region Size"]          = 200,
    ["Minimum Well Extension"]                      = 100,
    ["Minimum Implant Extension"]                   = 100,
    ["Minimum Active Space"]                        = 200,
    ["Minimum Gate Extension"]                      = 100,
    ["Minimum Gate Length"]                         = 200,
    ["Minimum Gate Width"]                          = 500,
    ["Minimum Gate XSpace"]                         = 300,
    ["Minimum Gate YSpace"]                         = 300,
    ["Minimum M1 Width"]                            = 200,
    ["Minimum M1 Space"]                            = 200,
    ["Minimum M2 Width"]                            = 200,
    ["Minimum M2 Space"]                            = 200,
    ["Minimum M3 Width"]                            = 400,
    ["Minimum M3 Space"]                            = 400,
    ["Minimum M4 Width"]                            = 600,
    ["Minimum M4 Space"]                            = 600,
}
