#! /usr/bin/lua

-- load API into global space
object     = require "object"
shape      = require "shape"
point      = require "point"
pointarray = require "pointarray"
layout     = require "layout"
graphics   = require "graphics"
pcell      = require "pcell"
generics   = require "generics"
bitop      = require "bitop"
celllib    = require "cell"

local techlib = require "technology"
local interface = require "interface"

local argparse = require "argparse"
local args = argparse.parse(arg)

-- prepare cell arguments
local cellargs = {}
for k, v in string.gmatch(table.concat(args.cellargs, " "), "(%w+)%s*=%s*(%S+)") do
    cellargs[k] = v
end

if not args.technology then
    print("no technology given")
    os.exit(1)
end
if not args.interface then
    print("no interface given")
    os.exit(1)
end
if not args.cell then
    print("no cell type given")
    os.exit(1)
end

techlib.load(args.technology)
interface.load(args.interface)

local cell, msg = celllib.create(args.cell, cellargs)

if not cell then
    print(string.format("error while creating cell, received: %s", msg))
    os.exit(1)
end

techlib.translate_metals(cell)
techlib.split_vias(cell)
techlib.create_via_geometries(cell)
techlib.map_layers(cell)
techlib.fix_to_grid(cell)

local filename = args.filename or "openPCells"
interface.write_cell(filename, cell)

-- vim: ft=lua
