function parameters()
end

function layout(main, _P)
    main:merge_into_shallow(pcell.create_layout("stdcells/1_inv_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/21_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/221_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/22_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/and_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/buf"))
    main:merge_into_shallow(pcell.create_layout("stdcells/cinv"))
    --main:merge_into_shallow(pcell.create_layout("stdcells/colstop"))
    main:merge_into_shallow(pcell.create_layout("stdcells/dff"))
    main:merge_into_shallow(pcell.create_layout("stdcells/dffnq"))
    main:merge_into_shallow(pcell.create_layout("stdcells/dffpq"))
    main:merge_into_shallow(pcell.create_layout("stdcells/dffprq"))
    main:merge_into_shallow(pcell.create_layout("stdcells/endcell"))
    main:merge_into_shallow(pcell.create_layout("stdcells/generic2bit"))
    main:merge_into_shallow(pcell.create_layout("stdcells/half_adder"))
    main:merge_into_shallow(pcell.create_layout("stdcells/harness"))
    main:merge_into_shallow(pcell.create_layout("stdcells/isogate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/latch_cell"))
    main:merge_into_shallow(pcell.create_layout("stdcells/latch"))
    main:merge_into_shallow(pcell.create_layout("stdcells/nand_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/nor_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/not_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/or_gate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/register"))
    --main:merge_into_shallow(pcell.create_layout("stdcells/rowstop"))
    main:merge_into_shallow(pcell.create_layout("stdcells/shiftregister"))
    main:merge_into_shallow(pcell.create_layout("stdcells/tbuf"))
    main:merge_into_shallow(pcell.create_layout("stdcells/test"))
    main:merge_into_shallow(pcell.create_layout("stdcells/tgate"))
    main:merge_into_shallow(pcell.create_layout("stdcells/xor_gate"))
end
