function parameters()
end

function layout(main, _P)
    local _1_inv_gate_ref = pcell.create_layout("stdcells/1_inv_gate")
    local _1_inv_gate_name = pcell.add_cell_reference(_1_inv_gate_ref, "1_inv_gate")
    main:add_child(_1_inv_gate_name)
    local _21_gate_ref = pcell.create_layout("stdcells/21_gate")
    local _21_gate_name = pcell.add_cell_reference(_21_gate_ref, "21_gate")
    main:add_child(_21_gate_name)
    local _221_gate_ref = pcell.create_layout("stdcells/221_gate")
    local _221_gate_name = pcell.add_cell_reference(_221_gate_ref, "221_gate")
    main:add_child(_221_gate_name)
    local _22_gate_ref = pcell.create_layout("stdcells/22_gate")
    local _22_gate_name = pcell.add_cell_reference(_22_gate_ref, "22_gate")
    main:add_child(_22_gate_name)
    local and_gate_ref = pcell.create_layout("stdcells/and_gate")
    local and_gate_name = pcell.add_cell_reference(and_gate_ref, "and_gate")
    main:add_child(and_gate_name)
    local buf_ref = pcell.create_layout("stdcells/buf")
    local buf_name = pcell.add_cell_reference(buf_ref, "buf")
    main:add_child(buf_name)
    local cinv_ref = pcell.create_layout("stdcells/cinv")
    local cinv_name = pcell.add_cell_reference(cinv_ref, "cinv")
    main:add_child(cinv_name)
    local colstop_ref = pcell.create_layout("stdcells/colstop")
    local colstop_name = pcell.add_cell_reference(colstop_ref, "colstop")
    main:add_child(colstop_name)
    local dffnq_ref = pcell.create_layout("stdcells/dffnq")
    local dffnq_name = pcell.add_cell_reference(dffnq_ref, "dffnq")
    main:add_child(dffnq_name)
    local dffpq_ref = pcell.create_layout("stdcells/dffpq")
    local dffpq_name = pcell.add_cell_reference(dffpq_ref, "dffpq")
    main:add_child(dffpq_name)
    local dffprq_ref = pcell.create_layout("stdcells/dffprq")
    local dffprq_name = pcell.add_cell_reference(dffprq_ref, "dffprq")
    main:add_child(dffprq_name)
    local endcell_ref = pcell.create_layout("stdcells/endcell")
    local endcell_name = pcell.add_cell_reference(endcell_ref, "endcell")
    main:add_child(endcell_name)
    local generic2bit_ref = pcell.create_layout("stdcells/generic2bit")
    local generic2bit_name = pcell.add_cell_reference(generic2bit_ref, "generic2bit")
    main:add_child(generic2bit_name)
    local half_adder_ref = pcell.create_layout("stdcells/half_adder")
    local half_adder_name = pcell.add_cell_reference(half_adder_ref, "half_adder")
    main:add_child(half_adder_name)
    local harness_ref = pcell.create_layout("stdcells/harness")
    local harness_name = pcell.add_cell_reference(harness_ref, "harness")
    main:add_child(harness_name)
    local isogate_ref = pcell.create_layout("stdcells/isogate")
    local isogate_name = pcell.add_cell_reference(isogate_ref, "isogate")
    main:add_child(isogate_name)
    local latch_cell_ref = pcell.create_layout("stdcells/latch_cell")
    local latch_cell_name = pcell.add_cell_reference(latch_cell_ref, "latch_cell")
    main:add_child(latch_cell_name)
    local latch_ref = pcell.create_layout("stdcells/latch")
    local latch_name = pcell.add_cell_reference(latch_ref, "latch")
    main:add_child(latch_name)
    local mux_ref = pcell.create_layout("stdcells/mux")
    local mux_name = pcell.add_cell_reference(mux_ref, "mux")
    main:add_child(mux_name)
    local nand_gate_ref = pcell.create_layout("stdcells/nand_gate")
    local nand_gate_name = pcell.add_cell_reference(nand_gate_ref, "nand_gate")
    main:add_child(nand_gate_name)
    local nor_gate_ref = pcell.create_layout("stdcells/nor_gate")
    local nor_gate_name = pcell.add_cell_reference(nor_gate_ref, "nor_gate")
    main:add_child(nor_gate_name)
    local not_gate_ref = pcell.create_layout("stdcells/not_gate")
    local not_gate_name = pcell.add_cell_reference(not_gate_ref, "not_gate")
    main:add_child(not_gate_name)
    local or_gate_ref = pcell.create_layout("stdcells/or_gate")
    local or_gate_name = pcell.add_cell_reference(or_gate_ref, "or_gate")
    main:add_child(or_gate_name)
    local register_ref = pcell.create_layout("stdcells/register")
    local register_name = pcell.add_cell_reference(register_ref, "register")
    main:add_child(register_name)
    --local rowstop_ref = pcell.create_layout("stdcells/rowstop")
    --local rowstop_name = pcell.add_cell_reference(rowstop_ref, "rowstop")
    --main:add_child(rowstop_name)
    local shiftregister_ref = pcell.create_layout("stdcells/shiftregister")
    local shiftregister_name = pcell.add_cell_reference(shiftregister_ref, "shiftregister")
    main:add_child(shiftregister_name)
    local tbuf_ref = pcell.create_layout("stdcells/tbuf")
    local tbuf_name = pcell.add_cell_reference(tbuf_ref, "tbuf")
    main:add_child(tbuf_name)
    local test_ref = pcell.create_layout("stdcells/test")
    local test_name = pcell.add_cell_reference(test_ref, "test")
    main:add_child(test_name)
    local tgate_ref = pcell.create_layout("stdcells/tgate")
    local tgate_name = pcell.add_cell_reference(tgate_ref, "tgate")
    main:add_child(tgate_name)
    local xor_gate_ref = pcell.create_layout("stdcells/xor_gate")
    local xor_gate_name = pcell.add_cell_reference(xor_gate_ref, "xor_gate")
    main:add_child(xor_gate_name)
end
