-- FIXME: the comparator cell is fairly complicated and not thoroughly checked
-- this layout has some bugs
return pcell.create_layout("analog/strongARM_comparator", "comparator", {
    gatelength = 500,
    gatespace = 320,
    clockfingers = 4,
    clockdummyfingers = 1,
    clockfingerwidth = 1000,
    clockinputgatewidth = 400,
    clockinputgatespace = 400,
    inputfingers = 4,
    inputfingerwidth = 1000,
    --inputdummyfingers = 1,
    latchfingers = 8,
    latchnfingerwidth = 1000,
    latchpfingerwidth = 1000,
    --latchcrossingoffset = 0,
    --latchgatewidth = 0,
    --latchgatespace = 0,
    --invdummyfingers = 1,
    --resetfingers = 2,
    --inputclocksdspace = 0,
    --invskip = 200,
    --resetgatewidth = 0,
    --resetgatespace = 0,
    --bufferfingers = 2,
    buffernfingerwidth = 1000,
    bufferpfingerwidth = 1000,
    rslatchnfingerwidth = 1000,
    rslatchpfingerwidth = 1000,
    --gstrwidth = 0,
    --sdwidth = 0,
    powerwidth = 800,
    powerspace = 300,
    outerdummyfingers = 4,
    --alternativeclockconnection = true,
})
