return pcell.create_layout("analog/current_starved_ringoscillator", "oscillator", {
    gatelength = 800,
    gatespace = 450,
    invfingers = 2,
    numinv = 5,
    pmosdiodefingers = 4,
    pmoszerofingers = 9,
    pmostunefingers = 2,
    pmosseparationfingers = 3,
    nmoscurrentfingers = 2,
    nmosdiodefingers = 4,
    mosdummieseverynth = 2,
    pfingerwidth = 2500,
    nfingerwidth = 1800,
    pfingercontactwidth = 1000,
    nfingercontactwidth = 1000,
    gstwidth = 400,
    gstspace = 600,
    powerwidth = 800,
    powerspace = 200,
    bufspacers = 2,
    buffingers = 4,
    drawguardrings = true,
    guardringwidth = 800,
    guardringspace = 800,
})
