local ldmos = pcell.create_layout("basic/ldmos", "_ldmos", {
    fingers = 2,
    fingerwidth = 2000,
    channeltype = "pmos",
    gatelength = 280,
    gatestrapwidth = 200,
    gatestrapspace = 200,
    gtopext = 100,
    gbotext = 100,
    sourcewidth = 200,
    sourcespace = 120,
    sourceskip = 50,
    sourcemetal = 3,
    drainwidth = 800,
    drainspace = 450,
    drainmetal = 4,
    extendall = 200,
    drawinnerguardring = true,
    guardringwidth = 200,
    guardringtopsep = 200,
    guardringbottomsep = 200,
    guardringleftsep = 200,
    guardringrightsep = 200,
})
return ldmos
