return pcell.create_layout("basic/mosfet", "mosfet", {
    channeltype = "pmos",
    flippedwell = false,
    vthtype = 1,
    oxidetype = 1,
    gatelength = 500,
    gatespace = 320,
    fingerwidth = 2000,
    fingers = 8,
    sdwidth = 200,
    drawtopgate = true,
    topgatewidth = 200,
    topgatespace = 200,
    sourcemetal = 1,
    connectsource = true,
    connectsourcewidth = 300,
    connectsourcespace = 200,
    drainmetal = 3,
    connectdrain = true,
    connectdrainwidth = 300,
    connectdrainspace = 200,
    extendall = 200,
    drawguardring = true,
    guardringsep = 1000,
    guardringfillwell = true,
})
