return pcell.create_layout("RF/mosfet", "rfmosfet", {
    channeltype = "nmos",
    flippedwell = false,
    gatelength = 200,
    gatespace = 200,
    fingerwidth = 1000,
    fingers = 16,
    gatestrapwidth = 200,
    gatestrapspace = 200,
    gatelandingwidth = 400,
    gatelandingspace = 400,
    sdwidth = 200,
    sdstrapwidth = 200,
    gatemetal = 3,
    sourcemetal = 2,
    drainmetal = 2,
    guardringwidth = 200,
    guardringxspace = 500,
    guardringyspace = 500,
    outerguardring_deepwelloffset = 200,
    activedummywidth = 120,
    activedummyspace = 200,
})
