return pcell.create_layout("analog/stacked_ringoscillator", "oscillator", {
    numrows = 4,
    --numdummyrows = 0,
    inv_per_row = 5,
    nand_row = 1,
    invfingers = 2,
    dummyfingers = 2,
    --bufferfingers = 8,
    gatelength = 800,
    gatespace = 400,
    --buffergatelength = 32,
    --buffergatespace = 84,
    --usegatecut = false,
    pwidth = 800,
    nwidth = 800,
    --bufferpwidth = 800,
    --buffernwidth = 800,
    --gatestrapwidth = 70,
    --gatestrapspace = 70,
    --sdwidth= 70,
    buffershift = 800,
    --powerlinemetal = 5,
})
