local cell = pcell.create_layout("analog/common_centroid", "_cell", {
    pattern = {
        { 3, 3, 3, 3 },
        { 1, 2, 2, 1 },
        { 2, 1, 1, 2 },
        { 3, 3, 3, 3 },
    },
    allow_unequal_rowshifts = true,
    channeltype = "nmos",
    fingers = 2,
    fingerwidth = 1250,
    xseparation = 1500,
    shortgates = false,
    gatelength = 1000,
    gatespace = 540,
    gatemetal = 1,
    gatelinemetal = 2,
    sourcemetal = 1,
    drainmetal = 2,
    interconnectmetal = 3,
    equalgatenets = false,
    usegateconnections = true,
    gateconnections = { { 1, 2, 3 } },
    equalsourcenets = false,
    usesourcestraps = true,
    usesourceconnections = true,
    sourceconnections = { { 1, 2, 3 } },
    usegloballines = true,
    globallines = {
        { pin = "source", net = 1 },
        { pin = "gate", net = 1 },
        { pin = "drain", net = 1 },
        { pin = "drain", net = 2 },
        { pin = "drain", net = 3 },
        --{ pin = "source", net = 2 },
    },
    annotate_interconnectlines = true,
    annotate_globallines = true,
    drawouterguardring = true,
    insertglobalguardringlines = true,
})

return cell
