local cell = object.create("nmoscascodemirror")

local cc = pcell.create_layout("analog/common_centroid", "_common_centroid", {
    pattern = {
        { 2, 1, 2 },
        { 2, 1, 2 },
    },
    channeltype = "nmos",
    vthtype = 1,
    oxidetype = 2,
    flippedwell = false,
    fingers = 2,
    fingerwidth = 2500,
    equalgatenets = true,
    shortgates = false,
    gatelength = 3000,
    gatespace = 540,
    gatemetal = 1,
    gatelinemetal = 2,
    fullgatevia = true,
    connectgatetosourcedrain = { { gate = 1, target = "drain1" }, },
    drainmetal = 1,
    sourcemetal = 1,
    interconnectmetal = 2,
    connectsourcesonbothsides = false,
    usesourcestraps = false,
    sourcedrainstrapwidth = 340,
    sourcedrainstrapspace = 340,
    sdwidth = 340,
    gatestrapwidth = 340,
    gatestrapspace = 340,
    gatestrapleftext = 0,
    gatestraprightext = 0,
    gatefeedlinewidth = 340,
    gatelinewidth = 340,
    gatelinespace = 340,
    gatelineviawidth = 340,
    drawinnerguardrings = false,
    drawouterguardring = true,
    guardringminxsep = 500,
    guardringminysep = 800,
    interconnectlinepos = "inline",
    interconnectlinewidth = 400,
    outputlinewidth = 2000,
    outputlinetopextend = 0,
    outputlinebotextend = 0,
    groupoutputlines = true,
    grouporder = "source_inside",
    gatestrapsincenter = false,
    connectgatesonbothsides = false,
    outerdummies = 0,
    extendalltop = 200,
    extendallbottom = 200,
    extendallleft = 200,
    extendallright = 200,
})

cell:merge_into(cc)

return cell
