return {
    channeltype = "nmos",
    flippedwell = true,
    gatelength = 300,
    gatespace = 500,
    fingerwidth = 1500,
    fingers = 4,
    drawtopgate = true,
    --topgatewidth = 500,
    sourcemetal = 2,
    connectsource = true,
    --connectsourcewidth = 500,
    drainmetal = 3,
    connectdrain = true,
    --connectdrainwidth = 500,
    drawguardring = true,
    grid = 500,
    centershapegrid = true,
}
