return {
    pattern = {
        { 1, 2, 2, 1 },
        { 2, 1, 1, 2 }
    },
    channeltype = "pmos",
    fingers = 4,
    fingerwidth = 1250,
    equalgatenets = false,
    gatelength = 1000,
    gatespace = 540,
    gatestrapsincenter = false,
    gatemetal = 1,
    gatelinemetal = 2,
    sourcemetal = 1,
    drainmetal = 1,
    interconnectmetal = 2,
    groupoutputlines = true,
    grouporder = "source_inside",
    usesourcestraps = true,
    sourcestrapsinside = true,
    vthtype = 1,
    oxidetype = 2,
    flippedwell = false,
    allow_unequal_rowshifts = true,
    sdwidth = 340,
    gatestrapwidth = 340,
    gatestrapspace = 340,
    gatefeedlinewidth = 400,
    gatelinewidth = 400,
    gatelinespace = 400,
    gatelineviawidth = 400,
    interconnectlinewidth = 400,
    outputlinewidth = 2000,
    interconnectlinepos = "offside",
    drawinnerguardrings = false,
    drawouterguardring = true,
    guardringfilloxidetype = true,
    guardringminxsep = 1000,
    guardringminysep = 1000,
    insertglobalguardringlines = true,
    annotate_lines = true,
}
