return {
    channeltype = "nmos",
    flippedwell = true,
    gatelength = 300,
    gatespace = 500,
    fingerwidth = 1500,
    fingers = 4,
    drawtopgate = true,
    sourcemetal = 3,
    sourcestraptopmetal = 4,
    connectsource = true,
    --drainviametal = 3,
    --drainstartmetal = 2,
    --drainendmetal = 3,
    drainmetal = 3,
    drainstraptopmetal = 4,
    connectdrain = true,
    usesdmetalwidthtable = true,
    sdmetalwidths = { 200, 300, 400, 600 },
    drawguardring = false,
    checkshorts = false,
}
