return {
    pattern = {
        { 0, 2, 2, 2, 2, 2 },
        { 2, 2, 1, 2, 2, 2 },
        { 2, 2, 2, 1, 2, 2 },
        { 2, 2, 2, 2, 2, 0 },
    },
    channeltype = "pmos",
    vthtype = 1,
    oxidetype = 2,
    flippedwell = false,
    fingers = 2,
    fingerwidth = 1250,
    equalgatenets = true,
    shortgates = false,
    gatelength = 1000,
    gatespace = 540,
    gatemetal = 1,
    gatelinemetal = 2,
    fullgatevia = true,
    connectgatetosourcedrain = { { gate = 1, target = "drain1" }, },
    drainmetal = 1,
    sourcemetal = 1,
    interconnectmetal = 2,
    connectsourcesonbothsides = false,
    usesourcestraps = false,
    sourcedrainstrapwidth = 340,
    sourcedrainstrapspace = 340,
    sdwidth = 340,
    gatestrapwidth = 340,
    gatestrapspace = 340,
    gatestrapleftext = 0,
    gatestraprightext = 0,
    gatelinewidth = 340,
    gatelinespace = 340,
    gatelineviawidth = 400,
    drawinnerguardrings = false,
    drawouterguardring = true,
    guardringminxsep = 500,
    guardringminysep = 800,
    guardringfillwell = true,
    guardringfilloxidetype = true,
    interconnectlinepos = "offside",
    interconnectlinewidth = 400,
    outputlinemode = "global",
    outputlinewidth = 2000,
    groupoutputlines = true,
    grouporder = "source_inside",
    gatestrapsincenter = false,
    connectgatesonbothsides = false,
    shortdummies = true,
    innerdummies = 0,
    outerdummies = 0,
    extendalltop = 200,
    extendallbottom = 200,
    extendallleft = 200,
    extendallright = 200,
}
