return {
    pattern = {
        { 2, 2, 1, 2, 2, 2 },
        { 2, 2, 2, 1, 2, 2 },
        { 2, 2, 1, 2, 2, 2 },
        { 2, 2, 2, 1, 2, 2 },
    },
    channeltype = "pmos",
    vthtype = 1,
    oxidetype = 2,
    flippedwell = false,
    allow_unequal_rowshifts = true,
    annotate_lines = true,
    fingers = 2,
    fingerwidth = 1250,
    equalgatenets = true,
    shortgates = false,
    gatelength = 1000,
    gatespace = 540,
    gatemetal = 1,
    gatelinemetal = 3,
    gatelinewidth = 400,
    fullgatevia = true,
    connectgatetosourcedrain = { { gate = 1, target = "drain1" }, },
    drainmetal = 2,
    sourcemetal = 2,
    interconnectmetal = 3,
    connectsourcesonbothsides = false,
    usesourcestraps = false,
    sourcedrainstrapwidth = 340,
    sourcedrainstrapspace = 340,
    guardringwidth = 500,
    drawinnerguardrings = false,
    drawouterguardring = true,
    guardringminxsep = 500,
    guardringminysep = 800,
    guardringfillwell = true,
    guardringfilloxidetype = true,
    insertglobalguardringlines = true,
    interconnectlinepos = "gate",
    interconnectlinewidth = 400,
    outputlinewidth = 2000,
}
