return {
    pattern = {
        { 0, 2, 5, 5, 5, 5, 1, 0 },
        { 6, 3, 5, 5, 5, 5, 4, 7 },
        { 7, 4, 5, 5, 5, 5, 3, 6 },
        { 0, 1, 5, 5, 5, 5, 2, 0 },
    },
    channeltype = "nmos",
    fingers = 4,
    fingerwidth = 1250,
    equalsourcenets = true,
    equalgatenets = false,
    gatelength = 1000,
    gatespace = 540,
    gatemetal = 1,
    gatelinemetal = 2,
    sourcemetal = 1,
    drainmetal = 1,
    interconnectmetal = 2,
    usegateconnections = true,
    gateconnections = { { 1, 2, 5 }, { 3 }, { 4 }, { 6, 7 } },
    sourcenets = { source1 = "gnd" },
    vthtype = 1,
    oxidetype = 2,
    flippedwell = false,
    allow_unequal_rowshifts = true,
    fingers = 2,
    sdwidth = 340,
    gatestrapwidth = 340,
    gatestrapspace = 340,
    gatefeedlinewidth = 400,
    gatelinewidth = 400,
    gatelinespace = 400,
    gatelineviawidth = 400,
    interconnectlinewidth = 400,
    outputlinewidth = 1000,
    gatemetal = 1,
    gatelinemetal = 2,
    sourcemetal = 1,
    drainmetal = 1,
    interconnectmetal = 2,
    usesourcestraps = false,
    sourcestrapsinside = true,
    interconnectlinepos = "offside",
    groupoutputlines = false,
    grouporder = "source_inside",
    drawinnerguardrings = false,
    drawouterguardring = true,
    guardringfilloxidetype = true,
    guardringminxsep = 1000,
    guardringminysep = 1000,
    insertglobalguardringlines = true,
    annotate_lines = true,
    shortdummies = true,
}
