/* Generated by Yosys 0.12 (git sha1 UNKNOWN, gcc 11.1.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os) */

(* top =  1  *)
(* src = "register_cell.sv:2.1-37.10" *)
module register_cell(chain_in, update, clk, reset, enable, chain_out, bit_out);
  (* src = "register_cell.sv:14.5-21.8" *)
  wire _00_;
  (* src = "register_cell.sv:14.5-21.8" *)
  wire _01_;
  (* src = "register_cell.sv:4.15-4.23" *)
  wire _02_;
  (* src = "register_cell.sv:9.16-9.25" *)
  wire _03_;
  (* src = "register_cell.sv:8.15-8.21" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "register_cell.sv:10.16-10.23" *)
  output bit_out;
  (* src = "register_cell.sv:4.15-4.23" *)
  input chain_in;
  (* src = "register_cell.sv:9.16-9.25" *)
  output chain_out;
  (* src = "register_cell.sv:6.15-6.18" *)
  input clk;
  (* src = "register_cell.sv:8.15-8.21" *)
  input enable;
  (* src = "register_cell.sv:13.9-13.14" *)
  wire ff_in;
  (* src = "register_cell.sv:7.15-7.20" *)
  input reset;
  (* src = "register_cell.sv:5.15-5.21" *)
  input update;
  not_gate inv (
    .I(_04_),
    .O(_05_)
  );
  nand_gate nand1 (
    .A(_02_),
    .B(_04_),
    .O(_06_)
  );
  nand_gate nand2 (
    .A(_03_),
    .B(_05_),
    .O(_07_)
  );
  nand_gate nand3 (
    .A(_06_),
    .B(_07_),
    .O(_01_)
  );
  (* src = "register_cell.sv:29.5-36.8" *)
  dffprq dff_out (
    .CLK(update),
    .D(ff_in),
    .Q(bit_out),
    .RESET(reset)
  );
  (* src = "register_cell.sv:24.5-26.8" *)
  dffnq dff_buf (
    .CLK(clk),
    .D(ff_in),
    .Q(chain_out)
  );
  (* src = "register_cell.sv:14.5-21.8" *)
  dffpq dff_in (
    .CLK(clk),
    .D(_00_),
    .Q(ff_in)
  );
  assign _03_ = chain_out;
  assign _02_ = chain_in;
  assign _04_ = enable;
  assign _00_ = _01_;
endmodule
