/* Generated by Yosys 0.12 (git sha1 UNKNOWN, gcc 12.1.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* hdlname = "\\serial_ctrl" *)
(* top =  1  *)
(* src = "../examples/place_and_route/serial_ctrl.sv:9.1-239.10" *)
module serial_ctrl(data_inout, clk, reset_in, count_reached_in, data_out_shift_reg_in, reset_count_out, update_shift_reg_out, reset_shift_reg_out, enable_shift_register);
  (* src = "../examples/place_and_route/serial_ctrl.sv:83.5-90.8" *)
  wire [1:0] _000_;
  (* src = "../examples/place_and_route/serial_ctrl.sv:108.5-118.8" *)
  wire _001_;
  (* src = "../examples/place_and_route/serial_ctrl.sv:42.5-49.8" *)
  wire _002_;
  (* src = "../examples/place_and_route/serial_ctrl.sv:68.5-75.8" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  (* force_downto = 32'd1 *)
  (* src = "../examples/place_and_route/serial_ctrl.sv:0.0-0.0|../examples/place_and_route/serial_ctrl.sv:157.13-230.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [3:0] _109_;
  (* src = "../examples/place_and_route/serial_ctrl.sv:121.71-121.78" *)
  wire [2:0] ack_out;
  (* src = "../examples/place_and_route/serial_ctrl.sv:27.71-27.82" *)
  wire [2:0] ack_out_pre;
  (* src = "../examples/place_and_route/serial_ctrl.sv:119.70-119.81" *)
  wire [2:0] ack_pattern;
  (* src = "../examples/place_and_route/serial_ctrl.sv:13.17-13.20" *)
  input clk;
  (* src = "../examples/place_and_route/serial_ctrl.sv:94.219-94.228" *)
  wire [2:0] cmd_count;
  (* src = "../examples/place_and_route/serial_ctrl.sv:93.219-93.232" *)
  wire [2:0] cmd_count_pre;
  (* src = "../examples/place_and_route/serial_ctrl.sv:79.74-79.81" *)
  wire [1:0] cmd_reg;
  (* src = "../examples/place_and_route/serial_ctrl.sv:78.74-78.85" *)
  wire [1:0] cmd_reg_pre;
  (* src = "../examples/place_and_route/serial_ctrl.sv:16.17-16.33" *)
  input count_reached_in;
  (* enum_value_0000 = "\\RESET_ST" *)
  (* enum_value_0001 = "\\RECOVER_ST" *)
  (* enum_value_0010 = "\\IDLE_ST" *)
  (* enum_value_0011 = "\\UPDATE_ST" *)
  (* enum_value_0100 = "\\RESET_REGISTER_ST" *)
  (* enum_value_0101 = "\\RCV_CMD_ST" *)
  (* enum_value_0110 = "\\ACK_CMD_ST" *)
  (* enum_value_0111 = "\\RCV_DATA_ST" *)
  (* enum_value_1000 = "\\SND_DATA_ST" *)
  (* enum_value_1001 = "\\PLACEHOLDER1_ST" *)
  (* enum_value_1010 = "\\PLACEHOLDER2_ST" *)
  (* enum_value_1011 = "\\PLACEHOLDER3_ST" *)
  (* enum_value_1100 = "\\PLACEHOLDER4_ST" *)
  (* enum_value_1101 = "\\PLACEHOLDER5_ST" *)
  (* enum_value_1110 = "\\PLACEHOLDER6_ST" *)
  (* enum_value_1111 = "\\PLACEHOLDER7_ST" *)
  (* src = "../examples/place_and_route/serial_ctrl.sv:32.18-32.28" *)
  (* wiretype = "\\ctrl_state_t" *)
  wire [3:0] curr_state;
  (* enum_value_0000 = "\\RESET_ST" *)
  (* enum_value_0001 = "\\RECOVER_ST" *)
  (* enum_value_0010 = "\\IDLE_ST" *)
  (* enum_value_0011 = "\\UPDATE_ST" *)
  (* enum_value_0100 = "\\RESET_REGISTER_ST" *)
  (* enum_value_0101 = "\\RCV_CMD_ST" *)
  (* enum_value_0110 = "\\ACK_CMD_ST" *)
  (* enum_value_0111 = "\\RCV_DATA_ST" *)
  (* enum_value_1000 = "\\SND_DATA_ST" *)
  (* enum_value_1001 = "\\PLACEHOLDER1_ST" *)
  (* enum_value_1010 = "\\PLACEHOLDER2_ST" *)
  (* enum_value_1011 = "\\PLACEHOLDER3_ST" *)
  (* enum_value_1100 = "\\PLACEHOLDER4_ST" *)
  (* enum_value_1101 = "\\PLACEHOLDER5_ST" *)
  (* enum_value_1110 = "\\PLACEHOLDER6_ST" *)
  (* enum_value_1111 = "\\PLACEHOLDER7_ST" *)
  (* src = "../examples/place_and_route/serial_ctrl.sv:33.18-33.33" *)
  (* wiretype = "\\ctrl_state_t" *)
  wire [3:0] curr_state_post;
  (* enum_value_0000 = "\\RESET_ST" *)
  (* enum_value_0001 = "\\RECOVER_ST" *)
  (* enum_value_0010 = "\\IDLE_ST" *)
  (* enum_value_0011 = "\\UPDATE_ST" *)
  (* enum_value_0100 = "\\RESET_REGISTER_ST" *)
  (* enum_value_0101 = "\\RCV_CMD_ST" *)
  (* enum_value_0110 = "\\ACK_CMD_ST" *)
  (* enum_value_0111 = "\\RCV_DATA_ST" *)
  (* enum_value_1000 = "\\SND_DATA_ST" *)
  (* enum_value_1001 = "\\PLACEHOLDER1_ST" *)
  (* enum_value_1010 = "\\PLACEHOLDER2_ST" *)
  (* enum_value_1011 = "\\PLACEHOLDER3_ST" *)
  (* enum_value_1100 = "\\PLACEHOLDER4_ST" *)
  (* enum_value_1101 = "\\PLACEHOLDER5_ST" *)
  (* enum_value_1110 = "\\PLACEHOLDER6_ST" *)
  (* enum_value_1111 = "\\PLACEHOLDER7_ST" *)
  (* src = "../examples/place_and_route/serial_ctrl.sv:31.18-31.32" *)
  (* wiretype = "\\ctrl_state_t" *)
  wire [3:0] curr_state_pre;
  (* src = "../examples/place_and_route/serial_ctrl.sv:12.17-12.27" *)
  inout data_inout;
  (* src = "../examples/place_and_route/serial_ctrl.sv:25.11-25.19" *)
  wire data_out;
  (* src = "../examples/place_and_route/serial_ctrl.sv:17.17-17.38" *)
  input data_out_shift_reg_in;
  (* src = "../examples/place_and_route/serial_ctrl.sv:24.11-24.21" *)
  wire enable_ack;
  (* src = "../examples/place_and_route/serial_ctrl.sv:21.18-21.39" *)
  output enable_shift_register;
  (* src = "../examples/place_and_route/serial_ctrl.sv:18.18-18.33" *)
  output reset_count_out;
  (* src = "../examples/place_and_route/serial_ctrl.sv:14.17-14.25" *)
  input reset_in;
  (* src = "../examples/place_and_route/serial_ctrl.sv:20.18-20.37" *)
  output reset_shift_reg_out;
  (* src = "../examples/place_and_route/serial_ctrl.sv:135.11-135.21" *)
  wire syncreset1;
  (* src = "../examples/place_and_route/serial_ctrl.sv:135.23-135.33" *)
  wire syncreset2;
  (* src = "../examples/place_and_route/serial_ctrl.sv:19.18-19.38" *)
  output update_shift_reg_out;
  not_gate _110_ (
    .I(curr_state[3]),
    .O(_061_)
  );
  not_gate _111_ (
    .I(curr_state[2]),
    .O(_062_)
  );
  not_gate _112_ (
    .I(cmd_reg[0]),
    .O(_063_)
  );
  not_gate _113_ (
    .I(count_reached_in),
    .O(_064_)
  );
  not_gate _114_ (
    .I(cmd_count[2]),
    .O(_065_)
  );
  not_gate _115_ (
    .I(curr_state_pre[1]),
    .O(_066_)
  );
  not_gate _116_ (
    .I(curr_state_pre[2]),
    .O(_067_)
  );
  not_gate _117_ (
    .I(curr_state_pre[3]),
    .O(_068_)
  );
  not_gate _118_ (
    .I(curr_state[1]),
    .O(_069_)
  );
  not_gate _119_ (
    .I(curr_state[0]),
    .O(_070_)
  );
  not_gate _120_ (
    .I(enable_ack),
    .O(_071_)
  );
  not_gate _121_ (
    .I(cmd_count_pre[1]),
    .O(_072_)
  );
  not_gate _122_ (
    .I(cmd_count_pre[2]),
    .O(_073_)
  );
  not_gate _123_ (
    .I(clk),
    .O(_004_)
  );
  not_gate _124_ (
    .I(ack_out[2]),
    .O(_074_)
  );
  not_gate _125_ (
    .I(ack_out[1]),
    .O(_075_)
  );
  nand_gate _126_ (
    .A(ack_out_pre[0]),
    .B(enable_ack),
    .O(_076_)
  );
  nand_gate _127_ (
    .A(data_out_shift_reg_in),
    .B(_071_),
    .O(_077_)
  );
  nand_gate _128_ (
    .A(_076_),
    .B(_077_),
    .O(data_inout)
  );
  nor_gate _129_ (
    .A(curr_state[3]),
    .B(curr_state[2]),
    .O(_078_)
  );
  nand_gate _130_ (
    .A(_061_),
    .B(_062_),
    .O(_079_)
  );
  nand_gate _131_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .O(_080_)
  );
  nor_gate _132_ (
    .A(_079_),
    .B(_080_),
    .O(_003_)
  );
  nor_gate _133_ (
    .A(curr_state[3]),
    .B(_062_),
    .O(_081_)
  );
  nand_gate _134_ (
    .A(_061_),
    .B(curr_state[2]),
    .O(_082_)
  );
  nand_gate _135_ (
    .A(curr_state[1]),
    .B(_070_),
    .O(_083_)
  );
  not_gate _136_ (
    .I(_083_),
    .O(_084_)
  );
  nand_gate _137_ (
    .A(_081_),
    .B(_084_),
    .O(reset_count_out)
  );
  nor_gate _138_ (
    .A(_072_),
    .B(_073_),
    .O(_085_)
  );
  nand_gate _139_ (
    .A(cmd_count_pre[0]),
    .B(_085_),
    .O(_086_)
  );
  nor_gate _140_ (
    .A(reset_count_out),
    .B(_086_),
    .O(_087_)
  );
  nand_gate _141_ (
    .A(cmd_reg[1]),
    .B(_087_),
    .O(_088_)
  );
  nor_gate _142_ (
    .A(curr_state[2]),
    .B(curr_state[0]),
    .O(_089_)
  );
  not_gate _143_ (
    .I(_089_),
    .O(_090_)
  );
  nor_gate _144_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .O(_091_)
  );
  not_gate _145_ (
    .I(_091_),
    .O(_092_)
  );
  nand_gate _146_ (
    .A(curr_state[3]),
    .B(_062_),
    .O(_093_)
  );
  nor_gate _147_ (
    .A(_092_),
    .B(_093_),
    .O(_094_)
  );
  nand_gate _148_ (
    .A(count_reached_in),
    .B(_094_),
    .O(_095_)
  );
  nor_gate _149_ (
    .A(_072_),
    .B(cmd_count_pre[0]),
    .O(_096_)
  );
  nand_gate _150_ (
    .A(cmd_count_pre[1]),
    .B(_073_),
    .O(_097_)
  );
  nor_gate _151_ (
    .A(cmd_count_pre[0]),
    .B(_097_),
    .O(_098_)
  );
  nand_gate _152_ (
    .A(_073_),
    .B(_096_),
    .O(_099_)
  );
  nand_gate _153_ (
    .A(_069_),
    .B(curr_state[0]),
    .O(_100_)
  );
  nor_gate _154_ (
    .A(_082_),
    .B(_100_),
    .O(_101_)
  );
  not_gate _155_ (
    .I(_101_),
    .O(_102_)
  );
  nand_gate _156_ (
    .A(_099_),
    .B(_101_),
    .O(_103_)
  );
  nand_gate _157_ (
    .A(_095_),
    .B(_103_),
    .O(_104_)
  );
  nor_gate _158_ (
    .A(_079_),
    .B(_083_),
    .O(_105_)
  );
  not_gate _159_ (
    .I(_105_),
    .O(_106_)
  );
  nand_gate _160_ (
    .A(data_inout),
    .B(_105_),
    .O(_107_)
  );
  nor_gate _161_ (
    .A(_080_),
    .B(_082_),
    .O(_108_)
  );
  nand_gate _162_ (
    .A(_064_),
    .B(_108_),
    .O(_011_)
  );
  nand_gate _163_ (
    .A(_107_),
    .B(_011_),
    .O(_012_)
  );
  nor_gate _164_ (
    .A(_104_),
    .B(_012_),
    .O(_013_)
  );
  nand_gate _165_ (
    .A(_088_),
    .B(_013_),
    .O(_109_[0])
  );
  nor_gate _166_ (
    .A(data_inout),
    .B(_106_),
    .O(_014_)
  );
  nand_gate _167_ (
    .A(curr_state[2]),
    .B(_092_),
    .O(_015_)
  );
  nand_gate _168_ (
    .A(_090_),
    .B(_015_),
    .O(_016_)
  );
  nand_gate _169_ (
    .A(_098_),
    .B(_101_),
    .O(_017_)
  );
  nand_gate _170_ (
    .A(_016_),
    .B(_017_),
    .O(_018_)
  );
  nor_gate _171_ (
    .A(_014_),
    .B(_018_),
    .O(_019_)
  );
  nor_gate _172_ (
    .A(cmd_reg[1]),
    .B(_086_),
    .O(_020_)
  );
  nor_gate _173_ (
    .A(reset_count_out),
    .B(_020_),
    .O(_021_)
  );
  nor_gate _174_ (
    .A(curr_state[3]),
    .B(_108_),
    .O(_022_)
  );
  nor_gate _175_ (
    .A(_091_),
    .B(_022_),
    .O(_023_)
  );
  nor_gate _176_ (
    .A(_021_),
    .B(_023_),
    .O(_024_)
  );
  nand_gate _177_ (
    .A(_019_),
    .B(_024_),
    .O(_109_[1])
  );
  nor_gate _178_ (
    .A(_063_),
    .B(_086_),
    .O(_025_)
  );
  nor_gate _179_ (
    .A(reset_count_out),
    .B(_025_),
    .O(_026_)
  );
  nand_gate _180_ (
    .A(_078_),
    .B(_091_),
    .O(_027_)
  );
  not_gate _181_ (
    .I(_027_),
    .O(_028_)
  );
  nor_gate _182_ (
    .A(_026_),
    .B(_028_),
    .O(_029_)
  );
  nor_gate _183_ (
    .A(_101_),
    .B(_012_),
    .O(_030_)
  );
  nand_gate _184_ (
    .A(_029_),
    .B(_030_),
    .O(_109_[2])
  );
  nand_gate _185_ (
    .A(_064_),
    .B(_094_),
    .O(_031_)
  );
  nor_gate _186_ (
    .A(cmd_reg[1]),
    .B(reset_count_out),
    .O(_032_)
  );
  nand_gate _187_ (
    .A(_025_),
    .B(_032_),
    .O(_033_)
  );
  nand_gate _188_ (
    .A(_031_),
    .B(_033_),
    .O(_109_[3])
  );
  nor_gate _189_ (
    .A(_067_),
    .B(curr_state_pre[3]),
    .O(_034_)
  );
  nor_gate _190_ (
    .A(curr_state_pre[0]),
    .B(curr_state_pre[1]),
    .O(_035_)
  );
  nand_gate _191_ (
    .A(_034_),
    .B(_035_),
    .O(_002_)
  );
  nor_gate _192_ (
    .A(_094_),
    .B(_108_),
    .O(_036_)
  );
  not_gate _193_ (
    .I(_036_),
    .O(enable_shift_register)
  );
  nor_gate _194_ (
    .A(curr_state_pre[0]),
    .B(_066_),
    .O(_037_)
  );
  nand_gate _195_ (
    .A(_034_),
    .B(_037_),
    .O(_038_)
  );
  not_gate _196_ (
    .I(_038_),
    .O(_039_)
  );
  nand_gate _197_ (
    .A(cmd_count[0]),
    .B(cmd_count[1]),
    .O(_040_)
  );
  nor_gate _198_ (
    .A(cmd_count[2]),
    .B(_040_),
    .O(_041_)
  );
  nor_gate _199_ (
    .A(cmd_count[1]),
    .B(_065_),
    .O(_042_)
  );
  nor_gate _200_ (
    .A(_041_),
    .B(_042_),
    .O(_043_)
  );
  nor_gate _201_ (
    .A(_038_),
    .B(_043_),
    .O(_001_)
  );
  nand_gate _202_ (
    .A(data_inout),
    .B(_101_),
    .O(_044_)
  );
  nand_gate _203_ (
    .A(cmd_reg[0]),
    .B(_102_),
    .O(_045_)
  );
  nand_gate _204_ (
    .A(_044_),
    .B(_045_),
    .O(_000_[0])
  );
  nand_gate _205_ (
    .A(cmd_reg[0]),
    .B(_101_),
    .O(_046_)
  );
  nand_gate _206_ (
    .A(cmd_reg[1]),
    .B(_102_),
    .O(_047_)
  );
  nand_gate _207_ (
    .A(_046_),
    .B(_047_),
    .O(_000_[1])
  );
  nand_gate _208_ (
    .A(_068_),
    .B(_037_),
    .O(_048_)
  );
  nor_gate _209_ (
    .A(curr_state_pre[2]),
    .B(_048_),
    .O(_049_)
  );
  nor_gate _210_ (
    .A(cmd_count[0]),
    .B(_049_),
    .O(_005_)
  );
  xnor_gate _211_ (
    .A(cmd_count[0]),
    .B(cmd_count[1]),
    .O(_050_)
  );
  nor_gate _212_ (
    .A(_049_),
    .B(_050_),
    .O(_006_)
  );
  xnor_gate _213_ (
    .A(_065_),
    .B(_040_),
    .O(_051_)
  );
  nor_gate _214_ (
    .A(_049_),
    .B(_051_),
    .O(_007_)
  );
  xor_gate _215_ (
    .A(curr_state_pre[3]),
    .B(curr_state_post[3]),
    .O(_052_)
  );
  xor_gate _216_ (
    .A(curr_state_pre[1]),
    .B(curr_state_post[1]),
    .O(_053_)
  );
  xor_gate _217_ (
    .A(curr_state_pre[2]),
    .B(curr_state_post[2]),
    .O(_054_)
  );
  xor_gate _218_ (
    .A(curr_state_pre[0]),
    .B(curr_state_post[0]),
    .O(_055_)
  );
  nor_gate _219_ (
    .A(_053_),
    .B(_055_),
    .O(_056_)
  );
  nor_gate _220_ (
    .A(_052_),
    .B(_054_),
    .O(_057_)
  );
  nand_gate _221_ (
    .A(_056_),
    .B(_057_),
    .O(_058_)
  );
  nand_gate _222_ (
    .A(_039_),
    .B(_058_),
    .O(_059_)
  );
  nand_gate _223_ (
    .A(_074_),
    .B(_059_),
    .O(_008_)
  );
  nand_gate _224_ (
    .A(ack_out[0]),
    .B(_059_),
    .O(_060_)
  );
  not_gate _225_ (
    .I(_060_),
    .O(_009_)
  );
  nand_gate _226_ (
    .A(_075_),
    .B(_059_),
    .O(_010_)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:95.5-102.8" *)
  dffnq _227_ (
    .CLK(clk),
    .D(_005_),
    .Q(cmd_count_pre[0])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:95.5-102.8" *)
  dffnq _228_ (
    .CLK(clk),
    .D(_006_),
    .Q(cmd_count_pre[1])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:95.5-102.8" *)
  dffnq _229_ (
    .CLK(clk),
    .D(_007_),
    .Q(cmd_count_pre[2])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:236.5-238.8" *)
  dffpq _230_ (
    .CLK(clk),
    .D(curr_state[0]),
    .Q(curr_state_post[0])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:236.5-238.8" *)
  dffpq _231_ (
    .CLK(clk),
    .D(curr_state[1]),
    .Q(curr_state_post[1])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:236.5-238.8" *)
  dffpq _232_ (
    .CLK(clk),
    .D(curr_state[2]),
    .Q(curr_state_post[2])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:236.5-238.8" *)
  dffpq _233_ (
    .CLK(clk),
    .D(curr_state[3]),
    .Q(curr_state_post[3])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:233.5-235.8" *)
  dffnq _234_ (
    .CLK(clk),
    .D(curr_state_pre[0]),
    .Q(curr_state[0])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:233.5-235.8" *)
  dffnq _235_ (
    .CLK(clk),
    .D(curr_state_pre[1]),
    .Q(curr_state[1])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:233.5-235.8" *)
  dffnq _236_ (
    .CLK(clk),
    .D(curr_state_pre[2]),
    .Q(curr_state[2])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:233.5-235.8" *)
  dffnq _237_ (
    .CLK(clk),
    .D(curr_state_pre[3]),
    .Q(curr_state[3])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:152.5-232.8" *)
  dffprq _238_ (
    .CLK(clk),
    .D(_109_[0]),
    .Q(curr_state_pre[0]),
    .RESET(syncreset2)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:152.5-232.8" *)
  dffprq _239_ (
    .CLK(clk),
    .D(_109_[1]),
    .Q(curr_state_pre[1]),
    .RESET(syncreset2)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:152.5-232.8" *)
  dffprq _240_ (
    .CLK(clk),
    .D(_109_[2]),
    .Q(curr_state_pre[2]),
    .RESET(syncreset2)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:152.5-232.8" *)
  dffprq _241_ (
    .CLK(clk),
    .D(_109_[3]),
    .Q(curr_state_pre[3]),
    .RESET(syncreset2)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:144.5-151.8" *)
  dffprq _242_ (
    .CLK(_004_),
    .D(syncreset1),
    .Q(syncreset2),
    .RESET(reset_in)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:136.5-143.8" *)
  dffprq _243_ (
    .CLK(clk),
    .D(1'h1),
    .Q(syncreset1),
    .RESET(reset_in)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:130.5-132.8" *)
  dffpq _244_ (
    .CLK(clk),
    .D(ack_out_pre[0]),
    .Q(ack_out[0])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:130.5-132.8" *)
  dffpq _245_ (
    .CLK(clk),
    .D(ack_out_pre[1]),
    .Q(ack_out[1])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:130.5-132.8" *)
  dffpq _246_ (
    .CLK(clk),
    .D(ack_out_pre[2]),
    .Q(ack_out[2])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:108.5-118.8" *)
  dffnq _247_ (
    .CLK(clk),
    .D(_001_),
    .Q(enable_ack)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:103.5-105.8" *)
  dffpq _248_ (
    .CLK(clk),
    .D(cmd_count_pre[0]),
    .Q(cmd_count[0])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:103.5-105.8" *)
  dffpq _249_ (
    .CLK(clk),
    .D(cmd_count_pre[1]),
    .Q(cmd_count[1])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:103.5-105.8" *)
  dffpq _250_ (
    .CLK(clk),
    .D(cmd_count_pre[2]),
    .Q(cmd_count[2])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:122.5-129.8" *)
  dffnq _251_ (
    .CLK(clk),
    .D(_008_),
    .Q(ack_out_pre[0])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:122.5-129.8" *)
  dffnq _252_ (
    .CLK(clk),
    .D(_009_),
    .Q(ack_out_pre[1])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:122.5-129.8" *)
  dffnq _253_ (
    .CLK(clk),
    .D(_010_),
    .Q(ack_out_pre[2])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:83.5-90.8" *)
  dffpq _254_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(cmd_reg_pre[0])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:83.5-90.8" *)
  dffpq _255_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(cmd_reg_pre[1])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:80.5-82.8" *)
  dffnq _256_ (
    .CLK(clk),
    .D(cmd_reg_pre[0]),
    .Q(cmd_reg[0])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:80.5-82.8" *)
  dffnq _257_ (
    .CLK(clk),
    .D(cmd_reg_pre[1]),
    .Q(cmd_reg[1])
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:68.5-75.8" *)
  dffpq _258_ (
    .CLK(clk),
    .D(_003_),
    .Q(update_shift_reg_out)
  );
  (* src = "../examples/place_and_route/serial_ctrl.sv:42.5-49.8" *)
  dffnq _259_ (
    .CLK(clk),
    .D(_002_),
    .Q(reset_shift_reg_out)
  );
  assign ack_pattern = 3'h5;
  assign data_out = data_inout;
endmodule
